SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_EXE_LINKER_FLAGS "")
set(CMAKE_C_FLAGS "")
set(CMAKE_CXX_FLAGS "")

include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(x86_64-elf-gcc GNU)
CMAKE_FORCE_CXX_COMPILER(x86_64-elf-gcc GNU)
set(CMAKE_ASM_NASM_COMPILER nasm)
set(CMAKE_LINKER x86_64-elf-gcc)
set(CMAKE_C_LINK_EXECUTABLE "x86_64-elf-gcc <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_FIND_ROOT_PATH ~/opt/cross)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

# Config only for the given architecture
set(SYSTEM_ARCH "x86_64")
